package view.container;

import javax.swing.JPanel;

public class MeasurementContainer extends JPanel {

	private static final long serialVersionUID = -6861914264277650997L;
	private final JPanel selectMeasurementPanel;
	private JPanel instructions;

	public MeasurementContainer(JPanel selectMeasurementPanel,
			JPanel instructions) {
		super();
		this.selectMeasurementPanel = selectMeasurementPanel;
		this.instructions = instructions;
		setLayout();
	}

	public void updateInstructions(JPanel instructions) {

		this.remove(this.instructions);
		this.remove(this.selectMeasurementPanel);

		this.instructions = instructions;
		setLayout();
	}

	/*
	 * This is code generated by the NetBeans GUI creator. It has been cut and
	 * pasted here to provide more flexibility.
	 */
	private void setLayout() {

		this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		javax.swing.GroupLayout measurementContainerLayout = new javax.swing.GroupLayout(
				this);
		this.setLayout(measurementContainerLayout);
		measurementContainerLayout
				.setHorizontalGroup(measurementContainerLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(instructions,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(selectMeasurementPanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE));
		measurementContainerLayout
				.setVerticalGroup(measurementContainerLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								measurementContainerLayout
										.createSequentialGroup()
										.addComponent(
												selectMeasurementPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												instructions,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(98, Short.MAX_VALUE)));
	}
}
