package view.panel;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

import view.FocusablePanel;


public class LoadImagePanel extends FocusablePanel {

	private static final long serialVersionUID = 1L;
	private final JLabel loadLabel = new JLabel("File:");
	private final JTextField loadField = new JTextField("Select...");
	private final JButton loadButton = new JButton("Browse");

	/**
	 * Basic constructor
	 */
	public LoadImagePanel() {
		super();
		setLayout();
	}

	public void setText(String text) {
		this.loadField.setText(text);
	}

	public JButton getBrowseButton() {
		return this.loadButton;
	}

	/*
	 * This is code generated by the NetBeans GUI creator. It has been cut and
	 * pasted here to provide more flexibility.
	 */
	private void setLayout() {

		this.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		javax.swing.GroupLayout loadLayout = new javax.swing.GroupLayout(this);
		this.setLayout(loadLayout);
		loadLayout
				.setHorizontalGroup(loadLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								loadLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(loadLabel)
										.addGap(18, 18, 18)
										.addComponent(
												loadField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												20, Short.MAX_VALUE)
										.addComponent(
												loadButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												75,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		loadLayout
				.setVerticalGroup(loadLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								loadLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												loadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																loadField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(loadLabel)
														.addComponent(
																loadButton))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}

}
